
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.example.game1.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLAS = 58;
  public static final int HEXADECIMAL = 51;
  public static final int CONFIG_C = 12;
  public static final int PLAYER_COLOR_C = 26;
  public static final int COR_CIERRA = 47;
  public static final int TARGETS_C = 36;
  public static final int HALL_COLOR = 21;
  public static final int COLUMN = 69;
  public static final int TYPE = 33;
  public static final int FLOOR = 55;
  public static final int HALL = 53;
  public static final int ROWS = 7;
  public static final int NAME = 5;
  public static final int BRICK = 52;
  public static final int BRICK_COLOR = 19;
  public static final int POSY_C = 32;
  public static final int LINE_C = 68;
  public static final int BOX_COLOR_C = 14;
  public static final int POSX_C = 30;
  public static final int ERRORS_C = 63;
  public static final int TARGET_COLOR = 17;
  public static final int BOXES = 39;
  public static final int INTEGER = 2;
  public static final int COLS_C = 10;
  public static final int CONFIG = 11;
  public static final int ERRORS = 62;
  public static final int ERROR = 57;
  public static final int DOS_PUNTOS = 42;
  public static final int CEIL = 56;
  public static final int TARGETS = 35;
  public static final int BOXES_C = 40;
  public static final int WORLD_C = 61;
  public static final int PUNTO_COMA = 43;
  public static final int WORLD = 60;
  public static final int PLAYER = 37;
  public static final int BRICK_COLOR_C = 20;
  public static final int PLAYER_COLOR = 25;
  public static final int COMA = 41;
  public static final int LLAVE_CIERRA = 45;
  public static final int ENTERO = 50;
  public static final int BOX_ON_TARGET_COLOR_C = 16;
  public static final int TYPE_C = 34;
  public static final int COLS = 9;
  public static final int DECIMAL = 59;
  public static final int BOARD_C = 28;
  public static final int SYM = 54;
  public static final int BOX_ON_TARGET_COLOR = 15;
  public static final int PLAYER_C = 38;
  public static final int LLAVE_ABRE = 44;
  public static final int EOF = 0;
  public static final int PUNTO = 48;
  public static final int TARGET_COLOR_C = 18;
  public static final int ERROR_X = 64;
  public static final int POSY = 31;
  public static final int LINE = 67;
  public static final int POSX = 29;
  public static final int BOX_COLOR = 13;
  public static final int UNDEFINED_COLOR = 23;
  public static final int error = 1;
  public static final int COLUMN_C = 70;
  public static final int VALUE_C = 66;
  public static final int ROWS_C = 8;
  public static final int ERROR_X_C = 71;
  public static final int HEAD = 3;
  public static final int HALL_COLOR_C = 22;
  public static final int CADENA = 4;
  public static final int STRING = 49;
  public static final int BOARD = 27;
  public static final int UNDEFINED_COLOR_C = 24;
  public static final int VALUE = 65;
  public static final int NAME_C = 6;
  public static final int COR_ABRE = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "HEAD",
  "CADENA",
  "NAME",
  "NAME_C",
  "ROWS",
  "ROWS_C",
  "COLS",
  "COLS_C",
  "CONFIG",
  "CONFIG_C",
  "BOX_COLOR",
  "BOX_COLOR_C",
  "BOX_ON_TARGET_COLOR",
  "BOX_ON_TARGET_COLOR_C",
  "TARGET_COLOR",
  "TARGET_COLOR_C",
  "BRICK_COLOR",
  "BRICK_COLOR_C",
  "HALL_COLOR",
  "HALL_COLOR_C",
  "UNDEFINED_COLOR",
  "UNDEFINED_COLOR_C",
  "PLAYER_COLOR",
  "PLAYER_COLOR_C",
  "BOARD",
  "BOARD_C",
  "POSX",
  "POSX_C",
  "POSY",
  "POSY_C",
  "TYPE",
  "TYPE_C",
  "TARGETS",
  "TARGETS_C",
  "PLAYER",
  "PLAYER_C",
  "BOXES",
  "BOXES_C",
  "COMA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "COR_ABRE",
  "COR_CIERRA",
  "PUNTO",
  "STRING",
  "ENTERO",
  "HEXADECIMAL",
  "BRICK",
  "HALL",
  "SYM",
  "FLOOR",
  "CEIL",
  "ERROR",
  "COMILLAS",
  "DECIMAL",
  "WORLD",
  "WORLD_C",
  "ERRORS",
  "ERRORS_C",
  "ERROR_X",
  "VALUE",
  "VALUE_C",
  "LINE",
  "LINE_C",
  "COLUMN",
  "COLUMN_C",
  "ERROR_X_C"
  };
}

