
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.mycompany.server_sokoban.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int BRICK_COLOR = 17;
  public static final int INTEGER = 8;
  public static final int TARGETS = 25;
  public static final int DOS_PUNTOS = 29;
  public static final int LPAREN = 6;
  public static final int BOX_COLOR = 14;
  public static final int TARGET_COLOR = 16;
  public static final int COR_CIERRA = 33;
  public static final int FLOOR = 40;
  public static final int ROWS = 11;
  public static final int MINUS = 3;
  public static final int CONFIG = 13;
  public static final int RPAREN = 7;
  public static final int COR_ABRE = 32;
  public static final int TYPE = 24;
  public static final int BOX_ON_TARGET_COLOR = 15;
  public static final int BOARD = 21;
  public static final int HALL = 38;
  public static final int PLUS = 2;
  public static final int HALL_COLOR = 18;
  public static final int DECIMAL = 43;
  public static final int BRICK = 37;
  public static final int EOF = 0;
  public static final int PLAYER = 26;
  public static final int COMILLAS = 9;
  public static final int SYM = 39;
  public static final int error = 1;
  public static final int COMA = 28;
  public static final int LLAVE_ABRE = 30;
  public static final int ERROR = 42;
  public static final int NAME = 10;
  public static final int POSY = 23;
  public static final int TIMES = 4;
  public static final int POSX = 22;
  public static final int COLS = 12;
  public static final int PUNTO = 34;
  public static final int BOXES = 27;
  public static final int HEXADECIMAL = 36;
  public static final int STRING = 35;
  public static final int LLAVE_CIERRA = 31;
  public static final int CEIL = 41;
  public static final int UNDEFINED_COLOR = 19;
  public static final int PLAYER_COLOR = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "INTEGER",
  "COMILLAS",
  "NAME",
  "ROWS",
  "COLS",
  "CONFIG",
  "BOX_COLOR",
  "BOX_ON_TARGET_COLOR",
  "TARGET_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "UNDEFINED_COLOR",
  "PLAYER_COLOR",
  "BOARD",
  "POSX",
  "POSY",
  "TYPE",
  "TARGETS",
  "PLAYER",
  "BOXES",
  "COMA",
  "DOS_PUNTOS",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "COR_ABRE",
  "COR_CIERRA",
  "PUNTO",
  "STRING",
  "HEXADECIMAL",
  "BRICK",
  "HALL",
  "SYM",
  "FLOOR",
  "CEIL",
  "ERROR",
  "DECIMAL"
  };
}

